version: '3.7'

services:
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flicket
      - POSTGRES_PASSWORD=Flicket888
      - POSTGRES_DB=flicket
    ports:
      - 5433:5432
  web:
    build: .
    command: python -m manage.py runserver
    volumes:
      - .:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
