version: '3.7'

services:
  db_ciml:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=clicket
      - POSTGRES_PASSWORD=Clicket2021
      - POSTGRES_DB=clicket_ciml
    networks:
      - omero
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/src/app/
    ports:
      - 5001:5001
    expose:
      - "5001"
    env_file:
      - ./.env.dev
    depends_on:
      - db_ciml
    networks:
      - omero
volumes:
  postgres_data:

networks:
  omero:

# python manage.py db migrate
# python -d manage.py run_set_up
# python manage.py runserver
