version: '3.7'

services:
  clicket_db:
    image: "postgres:11"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - backup:/backup
    environment:
      - POSTGRES_USER=flicket
      - POSTGRES_PASSWORD=Flicket888
      - POSTGRES_DB=flicket
    networks:
      - clicket
    ports:
      - 5432:5432
  web:
    build: .
    restart: always
    command: python manage.py runserver
    volumes:
      - .:/usr/src/app/
    environment:
      - POSTGRES_USER=flicket
      - POSTGRES_PASSWORD=Flicket888
      - POSTGRES_DB=flicket
    ports:
      - 127.0.0.1:5001:5001
    expose:
      - "5001"
    depends_on:
      - clicket_db
    networks:
      - clicket
volumes:
  postgres_data:
  backup:
    driver_opts:
      type: none
      device: /home/guillaume/data/backups/clicket
      o: bind
networks:
  clicket:


#
# python manage.py db migrate
# python -d manage.py run_set_up
# python manage.py runserver
