"""empty message

Revision ID: 905ba9f6d23d
Revises: 13b0fec5b6ac
Create Date: 2020-11-10 11:51:48.775036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ba9f6d23d'
down_revision = '13b0fec5b6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flicket_priorities')
    op.alter_column('flicket_request', 'request',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('flicket_procedure_stages', 'procedure_stage',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('flicket_request_stages', 'request_stage',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('flicket_requester_roles', 'requester_role',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_flicket_topic_referee'), 'flicket_topic', ['referee'], unique=False)
    op.create_index(op.f('ix_flicket_topic_requester'), 'flicket_topic', ['requester'], unique=False)
    op.drop_constraint('flicket_topic_ticket_priority_id_fkey', 'flicket_topic', type_='foreignkey')
    op.drop_column('flicket_topic', 'request_stage')
    op.drop_column('flicket_topic', 'procedure_stage')
    op.drop_column('flicket_topic', 'ticket_priority_id')
    op.drop_column('flicket_topic', 'requester_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('requester_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flicket_topic', sa.Column('ticket_priority_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flicket_topic', sa.Column('procedure_stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flicket_topic', sa.Column('request_stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('flicket_topic_ticket_priority_id_fkey', 'flicket_topic', 'flicket_priorities', ['ticket_priority_id'], ['id'])
    op.drop_index(op.f('ix_flicket_topic_requester'), table_name='flicket_topic')
    op.drop_index(op.f('ix_flicket_topic_referee'), table_name='flicket_topic')
    op.alter_column('flicket_requester_roles', 'requester_role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('flicket_request_stages', 'request_stage',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('flicket_procedure_stages', 'procedure_stage',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('flicket_request', 'request',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.create_table('flicket_priorities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flicket_priorities_pkey')
    )
    # ### end Alembic commands ###
